development:
  adapter: postgresql
  database: db_development
  encoding: unicode
  host: localhost
  username: 'artur'
  password: '1111'

test:
  adapter: postgresql
  database: db_test
  encoding: unicode
  host: localhost
  username: 'artur'
  password: '1111'

production:
  adapter: postgresql
  database: db_production
  encoding: unicode
  host: localhost
  username: 'artur'
  password: '1111'
